### ISSUE TITLE
Error: Not found: /api/auth/user

### ISSUE THREAD

**Issue by Blade67** [supabase/auth-helpers#215]
# Bug report

## Describe the bug

Getting `Error: Not found: /api/auth/user` when using a `__error.svelte` to catch errors.

```
Error: Not found: /api/auth/user
    at resolve (file:///E:/MyProject/.svelte-kit/runtime/server/index.js:3523:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handle (file:///E:/MyProject/node_modules/@supabase/auth-helpers-sveltekit/dist/handlers/logout.js:9:19)
    at async user (file:///E:/MyProject/node_modules/@supabase/auth-helpers-sveltekit/dist/handlers/user.js:7:21)
    at async handle (file:///E:/MyProject/node_modules/@supabase/auth-helpers-sveltekit/dist/handlers/callback.js:9:19)
    at async session (file:///E:/MyProject/node_modules/@supabase/auth-helpers-sveltekit/dist/handlers/session.js:77:20)
    at async respond (file:///E:/MyProject/.svelte-kit/runtime/server/index.js:3402:20)
    at async file:///E:/MyProject/node_modules/@sveltejs/kit/dist/vite.js:1539:22
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

 - Create a SvelteKit project with the Supabase Auth-Helpers-SvelteKit
 - Add a `__error.svelte` and log the error
 
## Expected behavior

No Errors.

## System information

- OS: Windows 10
- Browser: Chrome
- Version of supabase-js: 1.35.4
- Version of Node.js: v18.4.0

**Comment by silentworks** [comment]
This error was due to adding `console.error(error)` to the `load` function inside of the `__error.svelte` page. It's not an actual error as the hook handles the endpoint that it's not finding. But if you wish for this to not happen just create a `/api/auth/user.js` endpoint file and it will fix it.
