### ISSUE TITLE
Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined

### ISSUE THREAD

**Issue by MentalGear** [supabase/auth-helpers#310]
# Bug report

## Describe the bug
I followed [@supabase/auth-helpers-sveltekit](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) guide on how to integrate supabase-auth helpers with sveltekit.

Yet, when running the dev server, I get an internal error

```shell

Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
TypeError: Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
    at getRequestSupabaseClient (file:///.../node_modules/.pnpm/@supabase+auth-helpers-sveltekit@0.8.2_pkve26evzxp6f7qgiud6o7i2nm/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/supabase-request.js:10:13)
    at Proxy.getServerSession (file:///.../node_modules/.pnpm/@supabase+auth-helpers-sveltekit@0.8.2_pkve26evzxp6f7qgiud6o7i2nm/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/getServerSession.js:3:22)
    at load (/.../src/routes/+layout.server.ts:6:23)
    at load_server_data (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.50.1+vite@3.1.8/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:41)
    at respond_with_error (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.50.1+vite@3.1.8/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:40:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.50.1+vite@3.1.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:254:12)
    at async respond (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.50.1+vite@3.1.8/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:20)
    at async file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.515_svelte@3.50.1+vite@3.1.8/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:407:22

```

## To Reproduce
Followed the  [@supabase/auth-helpers-sveltekit](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) guide on how to integrate supabase-auth helpers with sveltekit on a clean install of sveltekit next@1.0.0-515.

## Expected behavior

Auth working

## Screenshots

/

## System information

- OS: macOS 15.5
- Browser (if applies) chrome, safari (latest)
- Version of supabase-js: 2.0.0
- Version of Node.js: 18
-  sveltekit next@1.0.0-515.

**Comment by f-gueguen** [comment]
You are very likely importing createClient from `supabase-js` instead of from `auth-helpers-sveltekit` (in lib/db.js)

**Comment by MentalGear** [comment]
Thank you! Dang, that was it indeed and was driving me nuts!

The reason was probably that I started with the  auth-helper guide on supabase's website, but noticed that it is out of sync with the latest version and came to the codebase to use the latest (readme.md).

**Comment by cnohara** [comment]
@f-gueguen I'm receiving this same issue despite my  `lin/db.ts` calling `import { createClient } from '@supabase/auth-helpers-sveltekit';`

I cannot find any instances of creating the client from supabase.

**Comment by VaughanG** [comment]
@cnohara I had that error despite correctly importing { createClient } from '@supabase/auth-helpers-sveltekit'.
What fixed it for me was adding _import '$lib/db'_; to hooks.client.ts and hooks.server.ts
