### ISSUE TITLE
Missing "./server" export in "@supabase/auth-helpers-sveltekit" package

### ISSUE THREAD

**Issue by wattsjs** [supabase/auth-helpers#323]
# Bug report

## Describe the bug

When building there is an error with the new auth-helpers 2.0 release.

```
[commonjs--resolver] Missing "./server" export in "@supabase/auth-helpers-sveltekit" package
[vite-plugin-svelte-kit] Missing "./server" export in "@supabase/auth-helpers-sveltekit" package
error during build:
Error: Missing "./server" export in "@supabase/auth-helpers-sveltekit" package
    at bail (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:33715:8)
    at resolve (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:33792:10)
    at resolveExports (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34853:12)
    at resolveDeepImport (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34871:31)
    at tryNodeResolve (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34584:20)
    at Object.resolveId (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34357:28)
    at Object.handler (file:///Users/frontend/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:45996:19)
    at file:///Users/frontend/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22710:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Dependancies:
"@supabase/auth-helpers-sveltekit": "^0.8.2",
"@supabase/supabase-js": "^2.0.0"

`yarn build` or `npm build`

## Expected behavior

Should build without issues

## System information

- Version of supabase-js: 2.0.0
- Version of Node.js: 18.6.0

**Comment by david-plugge** [comment]
Do you have any import that looks like `@supabase/auth-helpers-sveltekit/server` ?
If so please read the updated [docs](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md)

**Comment by wattsjs** [comment]
Bingo - thanks @david-plugge there was an import hidden in an used route from the previous version of auth-helpers
