### ISSUE TITLE
Export error in latest sveltekit-auth-helper

### ISSUE THREAD

**Issue by ak4zh** [supabase/auth-helpers#330]
```bash
Error: Missing "./server" export in "@supabase/auth-helpers-sveltekit" package
    at bail (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:33715:8)
    at resolve (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:33792:10)
    at resolveExports (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34853:12)
    at resolveDeepImport (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34871:31)
    at tryNodeResolve (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34584:20)
    at Context.resolveId (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34357:28)
    at Object.resolveId (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:41039:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.resolve (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:40808:23)
    at async normalizeUrl (file:///Users/ak4zh/CodeProjects/sveltekit-saas-starter/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:37589:34)
```

```
"@supabase/auth-helpers-sveltekit": "^0.8.2",
"@supabase/supabase-js": "2.0.0",
"@sveltejs/kit": "1.0.0-next.522",
```

**Comment by david-plugge** [comment]
The old version used two different exports. You probably have an import @supabase/auth-helpers-sveltekit/server somewhere in your code that should be updated
