### ISSUE TITLE
Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.

### ISSUE THREAD

**Issue by angezanetti** [supabase/auth-helpers#385]
# Bug report

## Describe the bug

I followed the [@supabase/auth-helpers-sveltekit](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) guide on how to integrate supabase-auth helpers with sveltekit.

It works, but when I stop my server and start it again with `npm run dev` I got the error: 

```
Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
TypeError: Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
    at getRequestSupabaseClient (file:///Users/xavier/Projects/remoteFr2/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/supabase-request.js:10:13)
    at Proxy.getServerSession (file:///Users/xavier/Projects/remoteFr2/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/getServerSession.js:3:22)
    at load (/src/routes/+layout.server.js:5:19)
    at load_server_data (file:///Users/xavier/Projects/remoteFr2/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:33:41)
    at respond_with_error (file:///Users/xavier/Projects/remoteFr2/node_modules/@sveltejs/kit/src/runtime/server/page/respond_with_error.js:41:32)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/xavier/Projects/remoteFr2/node_modules/@sveltejs/kit/src/runtime/server/index.js:261:12)
    at async respond (file:///Users/xavier/Projects/remoteFr2/node_modules/@sveltejs/kit/src/runtime/server/index.js:294:20)
    at async file:///Users/xavier/Projects/remoteFr2/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:397:22
```

But I'm 
## To Reproduce

Follow the guide, and restart your local server

## Expected behavior

It should handle the sessions
## System information

- OS:  macOS ventura M1
- Browser chrome
- Version of supabase-js: 2.1.0
- Version of Node.js: v16.16.0

**Comment by silentworks** [comment]
What version of the auth helper are your using? I can't replicate this issue in the latest version.

**Comment by david-plugge** [comment]
My guess is that you forgot to import `$lib/db` inside both hooks files 'hooks.client.js' and `hooks.server.js`.
We probably want to throw an error with a better error message if we call `getConfig` internally but `createClient` wasnt called before.

**Comment by david-plugge** [comment]
But i´m not able to reproduce the issue aswell.
The only thing i noticed is that i had to restart the dev server when i created `hooks.client.js` but that´s a sveltekit issue.

Could you share a reproduction?

**Comment by wozzashek** [comment]
I get this issue when trying to follow this in StackBlitz. Not seen it when running the tutorial on my local machine.

So not sure if this is a StackBlitz

See: https://stackblitz.com/edit/sveltejs-kit-template-default-jrbksc?file=package.json

You will need to add your own .env file

**Comment by david-plugge** [comment]
Take a look at this section:
https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#set-up-the-supabase-client

You need to import `lib/db` in both hooks files to actually load the client

**Comment by wozzashek** [comment]
Thanks @david-plugge you spotted my issue. I wonder if original poster also made the same mistake I did, having hooks files outside src folder.

**Comment by sjce-development** [comment]
Thanks a lot too, my issue was having the hook files inside of routes instead of the /src folder, this really helped a lot

**Comment by Olyno** [comment]
Hi 👋🏻 Having the same issue right now, here is my reproduction repository: https://github.com/Olyno/supabase-svelte-helper-auth-repro

This issue happens only on the http://localhost:3000/auh page for some reasons.

**Comment by Olyno** [comment]
Oh nice catch, i pushed it on the wrong branch 😅 fixed!

**Comment by david-plugge** [comment]
Alright, it seems like you are missing a `hooks.client.ts` file with the import from `$lib/db`. The import is necessary because the helpers must be initialized before any load functions run

**Comment by Olyno** [comment]
Indeed, the ``hooks.client.ts`` file was missing, it solves the issue, thank you! May i ask why do we need 2 kind of hooks to use the helper?

**Comment by ReeceLangerock** [comment]
I had the same error, and followed the suggestions from this issue and issue #310 and nothing was helping. I ended up wrapping `await getSupabase(event)` from `+layout.ts` in a try catch block and that "fixed" it. It seems that on initial load of the vite sveltekit server `getLoadSupabaseClient` is being called before `setConfig`.

**Comment by silentworks** [comment]
Code is outdated and no longer used.
