### ISSUE TITLE
(SvelteKit) Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined. 

### ISSUE THREAD

**Issue by CheapSmokes** [supabase/auth-helpers#402]
**Added the following code to +layout.ts**

`import type { LayoutLoad } from './$types'
import { getSupabase } from '@supabase/auth-helpers-sveltekit'

export const load: LayoutLoad = async (event) => {
  const { session } = await getSupabase(event)
  return { session }
}`

Then do `npm run dev`

**The following error is produced.**

`Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
TypeError: Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.
    at getLoadSupabaseClient (file:///***/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/supabase-load.js:5:13)
    at Proxy.getSupabase (file:///***/node_modules/@supabase/auth-helpers-sveltekit/dist/utils/getSupabase.js:16:26)
    at load (/***/src/routes/+layout.ts:5:28)
    at load_data (file:///***/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:105:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///***/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:193:13`

Can be overcome by commenting out code in +layout.ts, saving, then uncommenting and everything works as expected.

**Comment by wattsjs** [comment]
Check https://github.com/supabase/auth-helpers/issues/310
