### ISSUE TITLE
Error: Cookies can only be modified in a Server Action or Route Handler.

### ISSUE THREAD

**Issue by yannxaver** [supabase/auth-helpers#620]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Whenever the JWT expires and I refresh my app in localhost I get the following error:
> Error: Cookies can only be modified in a Server Action or Route Handler.

I do not call `cookies().set()` anywhere in my application, so I assume it must be internal Supabase behavior. However, I could not find any posts about this on GitHub or Discord. So, I am primarily posting here to see if others have encountered the same problem as well. My `middleware.ts` looks exactly like in the [example repository](https://github.com/supabase/supabase/tree/master/examples/auth/nextjs) provided.

Call stack: 
```shell
- error unhandledRejection: Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options
    at Proxy.callable (/Users/janscorl/Documents/Apps/recruiting/node_modules/.pnpm/next@13.4.17_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/adapters/request-cookies.js:42:15)
    at NextRouteHandlerAuthStorageAdapter.setCookie (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.7.4_@supabase+supabase-js@2.32.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:235:21)
    at NextRouteHandlerAuthStorageAdapter.setItem (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+auth-helpers-shared@0.4.1_@supabase+supabase-js@2.32.0/node_modules/@supabase/auth-helpers-shared/dist/index.js:275:14)
    at setItemAsync (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/lib/helpers.js:129:19)
    at SupabaseAuthClient._persistSession (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1555:43)
    at SupabaseAuthClient._saveSession (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1550:24)
    at SupabaseAuthClient._callRefreshToken (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1487:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupabaseAuthClient.__loadSession (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:885:40)
    at async SupabaseAuthClient._useSession (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:835:28)
    at async SupabaseAuthClient._emitInitialSession (webpack-internal:///(rsc)/./node_modules/.pnpm/@supabase+gotrue-js@2.47.0_encoding@0.1.13/node_modules/@supabase/gotrue-js/dist/main/GoTrueClient.js:1314:16) {
  digest: undefined
}
```

## Expected behavior

The error should not show up.

## System information

- OS: macOS
- Browser (if applies): Firefox
- Version of supabase-js: 2.32.0
- Version of Node.js: 18.16.0

## Additional context
None

**Comment by silentworks** [comment]
I've not been able to replicate this issue, also note your Stack trace mentions `NextRouteHandlerAuthStorageAdapter` which belongs to `createRouteHandlerClient` which should only be called inside of a route handler. I'm closing this out as we haven't had any other report of this and its not replicable from this side.

**Comment by chrisb2244** [comment]
I'm also hitting this, I think. When I navigate as a logged in user to my NextJS site, I hit a error 500 page, which disappears on refresh. Users who are not logged in do not observe this. It seems to trigger when I wait more than the refresh time between visits (1h+, with default settings via the app.supabase.io).

The error log from Vercel reads (with line breaks added by me):
```
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options",
"reason":{"errorType":"Error","errorMessage":"Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options",
"stack":["Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","    
at Proxy.callable (/var/task/frontend/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.prod.js:115:77320)","    
at _.setCookie (/var/task/frontend/.next/server/chunks/9790.js:1:6054)","    
at _.setItem (/var/task/frontend/.next/server/chunks/9790.js:1:13222)","    
at setItemAsync (/var/task/frontend/.next/server/chunks/9790.js:1:64115)","    
at SupabaseAuthClient._persistSession (/var/task/frontend/.next/server/chunks/9790.js:1:47952)","    
at SupabaseAuthClient._saveSession (/var/task/frontend/.next/server/chunks/9790.js:1:47853)","    
at SupabaseAuthClient._callRefreshToken (/var/task/frontend/.next/server/chunks/9790.js:1:46886)","    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    
at async SupabaseAuthClient.__loadSession (/var/task/frontend/.next/server/chunks/9790.js:1:36527)","    
at async SupabaseAuthClient._useSession (/var/task/frontend/.next/server/chunks/9790.js:1:35760)"]},
"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cookies can only be modified in a Server Action or Route Handler. Read more: https://nextjs.org/docs/app/api-reference/functions/cookies#cookiessetname-value-options","    
at process.<anonymous> (file:///var/runtime/index.mjs:1250:17)","    
at process.emit (node:events:526:35)","    
at emit (node:internal/process/promises:149:20)","    
at processPromiseRejections (node:internal/process/promises:283:27)","    
at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

I don't see any mention of the storageadapter described above, and my middleware is also similar to the example:

```
// middleware.ts
import { NextRequest, NextResponse } from 'next/server';
import { createMiddlewareClient } from '@supabase/auth-helpers-nextjs';
import type { Database } from './lib/sb_databaseModels';

export async function middleware(req: NextRequest) {
  if (process.env.NEXT_PUBLIC_MAINTENANCE_MODE === 'true') {
    return NextResponse.redirect('/');
  }

  const targetPath = req.nextUrl.pathname;
  const res = NextResponse.next();

  // This is called before returning to refresh the cookie-based session.
  const supabase = createMiddlewareClient<Database>({ req, res });
  const {
    data: { session }
  } = await supabase.auth.getSession();

  const pathsToFilter = ['/admin-pages-blah-blah'];

  if (!pathsToFilter.includes(targetPath)) {
    return res;
  }

  const denyAccess = () =>
    NextResponse.redirect(new URL('/access-denied', req.url));
  if (otherConditions) { // pseudo-code
    return denyAccess();
  }

  return res;
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - _next/data (json file for presentations)
     * - favicon.ico (favicon file)
     */
    '/((?!_next/static|_next/image|_next/data|favicon.ico).*)'
  ]
};

```

**Comment by chrisb2244** [comment]
In my case, I was triggering this message by accidentally calling something I'd defined as a ServerAction from within a Page (i.e. not as a form action or similar).
This thread put me on the right track: https://github.com/vercel/next.js/discussions/52096#discussioncomment-6341378

**Comment by gurvirsinghbaraich** [comment]
@yannxaver, Were you able to solve the issue. When ever I create a instance of server supabase client the same error occurs with me.

**Comment by yannxaver** [comment]
> @yannxaver, Were you able to solve the issue. When ever I create a instance of server supabase client the same error occurs with me.

Have a look at the linked thread in the comment before yours. This should solve your problem normally. I've stopped using Supabase Auth so I can't comment on it.

**Comment by gurvirsinghbaraich** [comment]
@yannxaver I have fixed the issue, it was the supabase helpers package and rewrote the helpers instead of using theirs.

**Comment by adeyemialameen04** [comment]
> @yannxaver I have fixed the issue, it was the supabase helpers package and rewrote the helpers instead of using theirs.

can u pls share what changes you made

**Comment by jmchaves** [comment]
I'm having a similar issue: https://github.com/supabase/supabase/issues/28489
