### ISSUE TITLE
Cookie is too large

### ISSUE THREAD

**Issue by mbalslow** [supabase/auth-helpers#643]
# Bug report

## Describe the bug

I have a SvelteKit app that uses the latest ```await supabase.auth.exchangeCodeForSession(code);``` auth logic with Azure as the provider and everything works fine. However, if I attempt to expand my "scopes" with ```offline_access``` to get the provider_refresh_token, I get the following error:

```
Error: Cookie "sb-weatotowrmtyjvnqaqki-auth-token" is too large, and will be discarded by the browser
    at set_internal (C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@sveltejs/kit/src/runtime/server/cookie.js:195:11)
    at Object.set (C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@sveltejs/kit/src/runtime/server/cookie.js:114:4)
    at SvelteKitServerAuthStorageAdapter.setCookie (file:///C:/Users/mbalslow/GitHub/basico-mit-website/node_modules/@supabase/auth-helpers-sveltekit/dist/index.js:80:24)
    at SvelteKitServerAuthStorageAdapter.setItem (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\auth-helpers-shared\dist\index.js:276:10)
    at setItemAsync (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:129:19)
    at SupabaseAuthClient._persistSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1328:43)
    at SupabaseAuthClient._saveSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1323:24)
    at SupabaseAuthClient._exchangeCodeForSession (C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:353:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\mbalslow\GitHub\basico-mit-website\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:643:28
```

As soon as I remove ```offline_access```, it works. It seems that too much data in put into the same cookie.

## Expected behavior

Maybe an option to have the provider details in a separate cookie or somehow be able to control how the session is stored in one or more cookies. The current implementation makes it impossible to get a hold of the provider_refresh_token, which is critical for our implementation.

**Comment by silentworks** [comment]
This is a known issue with cookies that they have a size limit. You can create your own cookie storage driver for the auth-helpers and handle cookie chunking in it. We had something we were working on to handle the chunking but we had issues in Safari.

**Comment by mbalslow** [comment]
Can you point me in some direction on how to do this @silentworks?

**Comment by mbalslow** [comment]
Can you point me in some direction on how to do this @silentworks?

**Comment by silentworks** [comment]
@mbalslow I have a working branch at the moment that will get merged in within the next few days to resolve this issue. Here is the PR https://github.com/supabase/auth-helpers/pull/653

**Comment by tobiassern** [comment]
@silentworks I see that this has now been merged, thank you for fixing it. But how do I use it, my current code is the same as is the same as in the tutorial -> https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit

What do i need to change, update in order to get this to work?

**Comment by silentworks** [comment]
@tobiassern the update you saw here was related to `@supabase/auth-helpers` and not `@supabase/ssr`. However we have now shipped this feature in the `@supabase/ssr` package too. But for SvelteKit there is a caveat in the `createBrowser` where you need to setup the `cookies.get` to handle chunking. I will add this to the guides soon.

**Comment by tobiassern** [comment]
@silentworks thank you for the update, looking forward to the updated guides.

**Comment by silentworks** [comment]
@tobiassern updated guides are now published.

**Comment by mattiasbonte** [comment]
Hello guys, I've implemented the chunking as described in the new package. But it seems now the logout action doesn't actually log out the user anymore. Does someone else encounter the same issue or is this something on my end?

**Comment by silentworks** [comment]
@mattiasbonte there was a bug in `0.0.8`, we've since reverted the change that caused the bug and released `0.0.9`. Please test out `0.0.9` and let us know if the issue has been resolved.

**Comment by mattiasbonte** [comment]
Hey @silentworks, I've downloaded the update and did a full test and now I see the `undefined` cookies are indeed gone and renamed to `sb-oqwjnxpmowajlgwaoqcs-auth-token.0` and `sb-oqwjnxpmowajlgwaoqcs-auth-token.1`. 

But the logout functionality is still broken. The thing is, when the `supabase.auth.signOut()` function is executed the cookie storage is still populated with the 2 cookies mentioned above. I assume this is the reason the logout fails?

**Comment by silentworks** [comment]
@mattiasbonte you will need to create a reproducible example of this as I've tested this on my side and cannot replicate this issue.

**Comment by mattiasbonte** [comment]
You can have this code in the `src/routes/layout.ts` file to reproduce.

```ts
	/**
	 * Supabase Client Side (Browser) Client.
	 * @info The server side client lives in `hooks.server.ts`
	 */
	const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		global: {
			fetch,
		},
		cookies: {
			get(key) {
				if (!isBrowser()) {
					return JSON.stringify(data.session);
				}
				const cookie = combineChunks(key, (name) => {
					const cookies = parse(document.cookie);
					return cookies[name];
				});
				return cookie;
			},
		},
	});
	
	// should directly sign the user out after instantiation?
	await supabase.auth.signOut();
       // but nothing happens.
```

@silentworks  So when I use the supabase `server client` to execute the `auth.signOut` action, everything works as expected.
It's when I use the `browser client` that it fails to work. I've tried to call my browser client in different parts of the app but all with the same result.

Does the signout action works on both your browserClient and serverClient? If yes, I will have to dig deeper.

**Comment by silentworks** [comment]
@mattiasbonte That is not how you would write a signout with the library. Please provide a reproducible Github repo, the snippets you are providing doesn't make much sense to someone else who doesn't have context of your project. Also you should probably create a new issue as this is no longer related to this original issue here.

**Comment by dvvolynkin** [comment]
@silentworks 
```typescript
export const createSupabaseRouteHandlerClient = (anon: boolean = true): SupabaseClient<Database> => {
  const cookieStore = cookies()

  return sbSSR.createServerClient<Database>(
    env.NEXT_PUBLIC_SUPABASE_URL!,
    anon ? env.NEXT_PUBLIC_SUPABASE_ANON_KEY! : env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      cookieOptions: getCookieOptions(),
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: sbSSR.CookieOptions) {
          console.log("cookie length", value.length)
          cookieStore.set({ name, value, ...options })
        },
        remove(name: string, options: sbSSR.CookieOptions) {
          cookieStore.set({ name, value: '', ...options })
        },
      },
    }
  )
}
```
cookie length in chunk is 3143

But after encoding in Set-Cookie header value length is 4262

**Comment by silentworks** [comment]
@dvvolynkin it would be useful to see the content your `getCookieOptions()` function returns.

**Comment by dvvolynkin** [comment]
```typescript
export const getCookieOptions = (): sbSSR.CookieOptions => {
  const hostname = new URL(env.NEXT_PUBLIC_APP_URL).hostname;
  const isHostSecure = env.NEXT_PUBLIC_APP_URL.startsWith('https://');
  const twelveMonths = 60 * 60 * 24 * 30 * 12;
  return {
    domain: hostname,
    path: '/',
    secure: isHostSecure,
    sameSite: 'none',
    maxAge: twelveMonths
  };
};

```

**Comment by sharkstate** [comment]
> @tobiassern the update you saw here was related to `@supabase/auth-helpers` and not `@supabase/ssr`. However we have now shipped this feature in the `@supabase/ssr` package too. But for SvelteKit there is a caveat in the `createBrowser` where you need to setup the `cookies.get` to handle chunking. I will add this to the guides soon.

Ive made the changes posted in the guide here:

https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout 

eg added:

import { combineChunks, createBrowserClient, isBrowser, parse } from '@supabase/ssr'

however, get:

The requested module '...@supabase_ssr.js?v=3acaaab5' does not provide an export named 'combineChunks'

**Comment by sharkstate** [comment]
> > @tobiassern the update you saw here was related to `@supabase/auth-helpers` and not `@supabase/ssr`. However we have now shipped this feature in the `@supabase/ssr` package too. But for SvelteKit there is a caveat in the `createBrowser` where you need to setup the `cookies.get` to handle chunking. I will add this to the guides soon.
> 
> Ive made the changes posted in the guide here:
> 
> https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout
> 
> eg added:
> 
> import { combineChunks, createBrowserClient, isBrowser, parse } from '@supabase/ssr'
> 
> however, get:
> 
> The requested module '[...@supabase_ssr.js](mailto:...@supabase_ssr.js)?v=3acaaab5' does not provide an export named 'combineChunks'

Sorry. Got it, 0.0.9

**Comment by DiegusAurelius** [comment]
> @tobiassern updated guides are now published.

Im having the same exact issue. IM using the SSR package 0.0.10, and Sveltekit 2.0.0. While authenticating with Facebook and Magic Link I get a 500 Internal error and "Cookie "sb-******-auth-token.1" is too large, and will be discarded by the browser. I tried the combineChunk method, but didn't work.

**Comment by badgifter** [comment]
Got same issue as well. For us, we were setting avatar_local="server.com/v1/storage/etc/etc/uuid/img_name_is_really_long_for_some_random_reason_prob_ai_gen_image.webp?width=200

I noticed when a person uploads a large name image for their avatar, once we set the avatar_url in their user_info, login no longer worked. I think the chunks being made didn't account for large key:value items in the raw user metadata?

**Comment by Raidus** [comment]
Same issue here. Any update on the issue?

**Comment by dantrain** [comment]
Until the chunking is fixed I found a way around this by gzipping the chunk values like this in the setter:

`zlib.gzipSync(Buffer.from(value, "utf-8")).toString("base64url")`

and in the getter the reverse:

`zlib.gunzipSync(Buffer.from(value, "base64url")).toString("utf-8")`

This seems to make them short enough to work for me, YMMV.

**Comment by thibistaken** [comment]
Same issue trying the PKCE email and oauth flows with Supabase SSR. Any update? Thanks!

**Comment by charislam** [comment]
@thibistaken which version of `@supabase/ssr` are you on? There was a fix in 0.1.0 related to this

**Comment by thibistaken** [comment]
I just upgraded from `0.0.5` to `0.1.0` and it seems it is working now? Will test it out a bit more. Thanks @charislam!

**Comment by mb21** [comment]
Am I right in assuming that we need the chunking only because we store so much stuff in the cookies, much of it redundant information? Wouldn't it be enough to store only the access token and refresh token? All the other info can be derived from that server-side?

**Comment by yulluone** [comment]
> @tobiassern the update you saw here was related to `@supabase/auth-helpers` and not `@supabase/ssr`. However we have now shipped this feature in the `@supabase/ssr` package too. But for SvelteKit there is a caveat in the `createBrowser` where you need to setup the `cookies.get` to handle chunking. I will add this to the guides soon.

Thank you for this,

I had been struggling with Google OAuth not working for hours, once I narrowed it down to a cookie-setting issue (the cookie was too large)... I came across this issue... A `@supabase/ssr` update from `0.0.5` to `0.3.0` fixed the issue.

**Comment by contactjavas** [comment]
Currently, this issue still exists even with latest supabase-js and supabase-ssr.
The effective solution for now is to minimalize the data in user_metadata field.

**Comment by gludington-amelia** [comment]
If I missed it, I apologize, but looking at this from the other direction, is there any means (and, preferably, guide) to stripping down/whitelisting claims that eventually get stored in the cookie?

Writing the entirety of app_metadata, user and user_metadata, and identities (for social logins) does not seem necessary for most/all applications, and, even if so, it seems like it would  be testing the limits of "strictly required" under the GDPR.

**Comment by gludington** [comment]
Following up mb21's earlier comment, is there an ability to configure/whitelist claims that go to the client (and therefore the cookie) to a minimal set, so that it is present in postgres for use, but not emitted to the client?  Size aside, some of the information in that cookie might test the boundaries of what GDPR would consider "strictly necessary."

**Comment by teamclouday** [comment]
I have a socketio setup that connects to a python server which uses [websockets](https://github.com/python-websockets/websockets/blob/01195322d2620a44039b716cb93c108c2ca9b6b9/src/websockets/legacy/http.py#L14). Apparently there's a hard limit of cookie size in header (8k) and my client keeps getting disconnected because of the large auth tokens created by supabase auth. Really hope there's a way to reduce the size.

**Comment by yekta** [comment]
We are having the same issue with supabase/ssr. This not only breaks Nginx default config but also breaks Cloudflare.

**Comment by oldbettie** [comment]
This seems to be a consistent issue. Why don't you store just the `access_token, refresh_token` in the original cookie and any other stuff can just do in cookie-name.1???? that seems pretty logical and simple it would not break everytime it chunks the cookie

**Comment by danperks** [comment]
I'm using Nuxt, and I've just gone through and updated all my project dependencies to the latest version.
Interestingly,  I wasn't having this issue before, but seemingly at random, I'm getting "Bad Request" errors stating my request header field exceeds server limit from NGINX.

Seems to match @yekta's issue, and this is all on the latest versions of packages.

**Comment by oof2win2** [comment]
Same happens to me here. Vercel middleware is fully discarding all requests.
