### ISSUE TITLE
"Cannot read properties of undefined (reading 'getHeader')" console spam when using the client with NextJS 14

### ISSUE THREAD

**Issue by sergiofra98** [supabase/auth-helpers#665]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I just decided to upgrade my dependencies on my app, i upgraded to nextjs 14 along with supabase from:

```
    "@supabase/auth-helpers-nextjs": "0.5.7",
    "@supabase/auth-helpers-react": "0.3.1",
    "@supabase/supabase-js": "2.15.0",
    "next": "13.2.4",
```

to:

```
    "@supabase/auth-helpers-nextjs": "0.8.4",
    "@supabase/auth-helpers-react": "0.4.2",
    "@supabase/supabase-js": "2.38.4",
    "next": "14.0.1",
```

Not much changed in the app except the patches i had to do for the breaking changes, such as the renaming of the client creator and the authentication flow. It works like a charm, except for the following console spam:

```
⨯ unhandledRejection: TypeError: Cannot read properties of undefined (reading 'getHeader')
   at NextServerAuthStorageAdapter.getCookie (/home/sergio/trabajo/node_modules/@supabase/auth-helpers-nextjs/src/pagesServerClient.ts:28:57)
   at NextServerAuthStorageAdapter.getItem (/home/sergio/trabajo/node_modules/@supabase/auth-helpers-shared/src/cookieAuthStorageAdapter.ts:24:22)
   at getItemAsync (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/lib/helpers.ts:125:31)
   at SupabaseAuthClient.__loadSession (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:985:46)
   at SupabaseAuthClient._useSession (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:943:33)
   at SupabaseAuthClient._emitInitialSession (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:1499:23)
   at <anonymous> (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:1491:14)
   at <anonymous> (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:875:26)
   at SupabaseAuthClient.lockNoOp (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:104:16)
   at SupabaseAuthClient._acquireLock (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:869:25)
   at <anonymous> (/home/sergio/trabajo/node_modules/@supabase/gotrue-js/src/GoTrueClient.ts:1490:18)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

I get this error in the hundreds and i cant deploy my app to vercel because it results in every single request erroring out in code 500.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Upgrade to the latest NextJS.
2. Upgrade to the latest supabase-js and the auth helpers.
3. Run code that depends on the Supabase client.
4. See the console spam.

## Expected behavior

No console spam. If the getting of the header or cookie fails, it should do so gracefully, the problematic code is designed to return null or undefined.

## System information

- OS: Ubuntu 20.04
- Browser: Firefox
- Version of supabase-js: 2.38.4
- Version of Node.js: v18.18.2

## Additional context

The problematic code is the following `@supabase/auth-helpers-nextjs/src/pagesServerClient.ts:28:57`, maybe some checking if the res of the context is null before trying to access it? some more guard rails could help the issue. I suspect its a compatability issue with Nextjs 14

```
	protected getCookie(name: string): string | null | undefined {
		const setCookie = splitCookiesString(this.context.res.getHeader('set-cookie')?.toString() ?? '')
			.map((c) => parseCookies(c)[name])
			.find((c) => !!c);

		const value = setCookie ?? this.context.req.cookies[name];
		return value;
	}
```

**Comment by sergiofra98** [comment]
I made an attempt of fixing it at the PR [667](https://github.com/supabase/auth-helpers/pull/667)
